name: Publish to GH Pages
on:
  push:
    branches:
      - '[0-9]*.[0-9]*' # Match version names x*.y*. This is not regex supported so it would match 1ab.2bc.3asd, but not preview/1.2.3
permissions:
  contents: write
env:
  baseurl: /kdrs-search-and-view-docs/
  latest_branch: x.y.z
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

        # We only want the most recent version to be deployed to root, so find the most recent version
      - name: Find most recent version
        run: |
          git fetch --all
          # get all branches, filter matching origin/x.y.z where xyz are integers, remove origin, sort by version, only get last which is most recent, remove space
          echo latest_branch=$(git branch -r | grep -E 'origin/([0-9]+)\.([0-9]+)$' | sed 's|origin/||' | sort -V | tail -n1 | tr -d '[:space:]') >> $GITHUB_ENV

      # ---------------------------------------------------------
      # BUILD AND DEPLOY TO ROOT. This part only runs if the branch pushed to is the latest version.  
      # ---------------------------------------------------------
      - name: Build with Jekyll
        if: ${{ env.latest_branch == github.ref_name }} 
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: _site

      - name: Deploy to root if this is the most recent version
        if: ${{ env.latest_branch == github.ref_name }} 
        uses: JamesIves/github-pages-deploy-action@v4.3.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          target-folder: /
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            version/*
      # ---------------------------------------------------------    
      # BUILD AND DEPLOY TO /version/x.y.z. This part always runs.
      # ---------------------------------------------------------
      - name: Set baseurl # To make versions have hyperlinks relative to their directories, overwrite jekyll baseurl with (baseurl)/version/x.y.z
        run: |
          echo '' >> _config.yml
          echo baseurl: $(echo '${{env.baseurl}}' | cut -d / -f 1,2)/version/${{github.ref_name}} >> _config.yml

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: _site

      - name: Deploy to versions
        uses: JamesIves/github-pages-deploy-action@v4.3.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          target-folder: /version/${{github.ref_name}}
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            !/version/${{github.ref_name}}