name: Publish to GH Pages
on:
  push:
    branches:
      - master
  release:
    types:
      - published
permissions:
  contents: write
env:
  kdrsInnsynDocVersionPath: /
  baseurl: /test-kdrs-innsyn-docs/
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Update kdrsInnsynDocVersionPath for releases
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo kdrsInnsynDocVersionPath=/version/$(echo $GITHUB_REF | cut -d / -f 3 | cut -d v -f 2- | cut -d . -f 1,2) >> $GITHUB_ENV

      # - name: Update kdrsInnsynDocVersionPath for non-main branches
      #   if: ${{ github.ref_type == 'branch' && github.ref_name != 'master'}}
      #   run: echo kdrsInnsynDocVersionPath=/preview >> $GITHUB_ENV

      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: Set baseurl # To make versions have hyperlinks relative to their directories, overwrite baseurl with version
        run: |
          echo '' >> _config.yml
          echo baseurl: $(echo '${{env.baseurl}}' | cut -d / -f 1,2)${{env.kdrsInnsynDocVersionPath}} >> _config.yml

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: _site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
          target-folder: ${{ env.kdrsInnsynDocVersionPath }}
          clean: true # Automatically remove deleted files from the deploy branch
          clean-exclude: |
            version/*
    
  # deploy:
  #   permissions:
  #     contents: read
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4